[workspace]
members = [
  "crates/regex-core",
  "crates/regex-cli",
]
resolver = "2"

[workspace.package]
<<<<<<< HEAD
version = "2.0.0"
=======
version = "1.2.2"
>>>>>>> bd41ef71be90f57e8d41b743830453a83c8d44a7
edition = "2024"
