[package]
name = "regex-core"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = "1.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "regex_engine_bench"
harness = false
