[package]
name = "regex-core"
version.workspace = true
edition.workspace = true

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "regex_engine_bench"
harness = false

[dependencies]
thiserror = "2.0.18"
